#include "sp_regions.h"
#include "region_metadata.h"

/* One hook context shared by all SP regions. */
region_control sp_control;

/* Structure is manual; each initializer gets compile-time hook metadata. */
region_info sp_regions[SP_REGION_COUNT] = {
  [SP_P_ADD] = REGION_INFO(SP_P_ADD, -1, 1, 0),
  [SP_P_ERROR_NORM] = REGION_INFO(SP_P_ERROR_NORM, -1, 0, 0),
  [SP_F_ERROR_NORM_1] = REGION_INFO(SP_F_ERROR_NORM_1, SP_P_ERROR_NORM, 0, 1),
  [SP_P_RHS_NORM] = REGION_INFO(SP_P_RHS_NORM, -1, 0, 0),
  [SP_F_RHS_NORM_1] = REGION_INFO(SP_F_RHS_NORM_1, SP_P_RHS_NORM, 0, 1),
  [SP_P_EXACT_RHS] = REGION_INFO(SP_P_EXACT_RHS, -1, 0, 0),
  [SP_F_EXACT_RHS_1] = REGION_INFO(SP_F_EXACT_RHS_1, SP_P_EXACT_RHS, 0, 0),
  [SP_F_EXACT_RHS_2] = REGION_INFO(SP_F_EXACT_RHS_2, SP_P_EXACT_RHS, 0, 1),
  [SP_F_EXACT_RHS_4] = REGION_INFO(SP_F_EXACT_RHS_4, SP_P_EXACT_RHS, 0, 0),
  [SP_F_EXACT_RHS_5] = REGION_INFO(SP_F_EXACT_RHS_5, SP_P_EXACT_RHS, 0, 1),
  [SP_P_INITIALIZE] = REGION_INFO(SP_P_INITIALIZE, -1, 0, 0),
  [SP_F_INITIALIZE_1] = REGION_INFO(SP_F_INITIALIZE_1, SP_P_INITIALIZE, 0, 0),
  [SP_F_INITIALIZE_2] = REGION_INFO(SP_F_INITIALIZE_2, SP_P_INITIALIZE, 0, 1),
  [SP_F_INITIALIZE_4] = REGION_INFO(SP_F_INITIALIZE_4, SP_P_INITIALIZE, 0, 1),
  [SP_P_NINVR] = REGION_INFO(SP_P_NINVR, -1, 1, 0),
  [SP_P_PINVR] = REGION_INFO(SP_P_PINVR, -1, 1, 0),
  [SP_P_COMPUTE_RHS] = REGION_INFO(SP_P_COMPUTE_RHS, -1, 0, 0),
  [SP_F_COMPUTE_RHS_1] = REGION_INFO(SP_F_COMPUTE_RHS_1, SP_P_COMPUTE_RHS, 0, 1),
  [SP_F_COMPUTE_RHS_3] = REGION_INFO(SP_F_COMPUTE_RHS_3, SP_P_COMPUTE_RHS, 0, 1),
  [SP_F_COMPUTE_RHS_5] = REGION_INFO(SP_F_COMPUTE_RHS_5, SP_P_COMPUTE_RHS, 0, 0),
  [SP_F_COMPUTE_RHS_6] = REGION_INFO(SP_F_COMPUTE_RHS_6, SP_P_COMPUTE_RHS, 0, 1),
  [SP_F_COMPUTE_RHS_8] = REGION_INFO(SP_F_COMPUTE_RHS_8, SP_P_COMPUTE_RHS, 0, 1),
  [SP_P_TXINVR] = REGION_INFO(SP_P_TXINVR, -1, 1, 0),
  [SP_P_TZETAR] = REGION_INFO(SP_P_TZETAR, -1, 1, 0),
  [SP_P_X_SOLVE] = REGION_INFO(SP_P_X_SOLVE, -1, 1, 0),
  [SP_P_Y_SOLVE] = REGION_INFO(SP_P_Y_SOLVE, -1, 1, 0),
  [SP_P_Z_SOLVE] = REGION_INFO(SP_P_Z_SOLVE, -1, 1, 0),
};
