#ifndef NPB_FT_REGION_INFO_H
#define NPB_FT_REGION_INFO_H

#include "region_timers.h"

enum {
  R_EVOLVE_PARALLEL_FOR_1 = 0,
  R_CFFTS1_PARALLEL_FOR_1 = 1,
  R_CFFTS2_PARALLEL_FOR_1 = 2,
  R_CFFTS3_PARALLEL_FOR_1 = 3,
  R_CHECKSUM_PARALLEL_1 = 4,
  R_CHECKSUM_FOR_1 = 5,
  R_COUNT = 6
};

#endif
