#ifndef NPB_BT_REGION_INFO_H
#define NPB_BT_REGION_INFO_H

/* Fixed timer indexes for the instrumented OpenMP regions. */
enum {
  R_ADD_PARALLEL,
  R_COMPUTE_RHS_PARALLEL,
  R_COMPUTE_RHS_FOR_1,
  R_COMPUTE_RHS_FOR_2,
  R_COMPUTE_RHS_FOR_3,
  R_COMPUTE_RHS_FOR_4,
  R_COMPUTE_RHS_FOR_5,
  R_COMPUTE_RHS_FOR_6,
  R_COMPUTE_RHS_FOR_7,
  R_COMPUTE_RHS_FOR_8,
  R_X_SOLVE_PARALLEL,
  R_Y_SOLVE_PARALLEL,
  R_Z_SOLVE_PARALLEL,
  R_COUNT
};

#endif
