#ifndef NPB_MG_REGION_INFO_H
#define NPB_MG_REGION_INFO_H

#include "region_timers.h"

enum {
  R_PSINV_PARALLEL_FOR_1 = 0,
  R_RESID_PARALLEL_FOR_1 = 1,
  R_RPRJ3_PARALLEL_FOR_1 = 2,
  R_INTERP_PARALLEL_FOR_1 = 3,
  R_INTERP_PARALLEL_1 = 4,
  R_INTERP_FOR_1 = 5,
  R_INTERP_FOR_2 = 6,
  R_NORM2U3_PARALLEL_1 = 7,
  R_NORM2U3_FOR_1 = 8,
  R_COMM3_PARALLEL_1 = 9,
  R_COMM3_FOR_1 = 10,
  R_COMM3_FOR_2 = 11,
  R_ZERO3_PARALLEL_FOR_1 = 12,
  R_COUNT = 13
};

#endif
